# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{ether_shell}
  s.version = ""

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Victor Costan"]
  s.date = %q{2011-03-22}
  s.default_executable = %q{ether_shell}
  s.description = %q{IRB session specialized for testing Ethernet devices}
  s.email = %q{victor@costan.us}
  s.executables = ["ether_shell"]
  s.extra_rdoc_files = [
    "LICENSE.txt",
    "README.rdoc"
  ]
  s.files = [
    ".document",
    ".project",
    ".rspec",
    "Gemfile",
    "Gemfile.lock",
    "LICENSE.txt",
    "README.rdoc",
    "Rakefile",
    "bin/ether_shell",
    "lib/ether_shell.rb",
    "lib/ether_shell/expectation_error.rb",
    "lib/ether_shell/high_socket.rb",
    "lib/ether_shell/raw_socket.rb",
    "lib/ether_shell/shell_dsl.rb",
    "spec/ether_shell/high_socket_spec.rb",
    "spec/ether_shell/raw_socket_spec.rb",
    "spec/ether_shell/shell_dsl_spec.rb",
    "spec/ether_shell_spec.rb",
    "spec/spec_helper.rb",
    "spec/support/raw_socket_stub.rb",
    "spec/support/shell_stub.rb"
  ]
  s.homepage = %q{http://github.com/pwnall/ether_shell}
  s.licenses = ["MIT"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.6.0}
  s.summary = %q{IRB session specialized for testing Ethernet devices}
  s.test_files = [
    "spec/ether_shell/high_socket_spec.rb",
    "spec/ether_shell/raw_socket_spec.rb",
    "spec/ether_shell/shell_dsl_spec.rb",
    "spec/ether_shell_spec.rb",
    "spec/spec_helper.rb",
    "spec/support/raw_socket_stub.rb",
    "spec/support/shell_stub.rb"
  ]

  if s.respond_to? :specification_version then
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_development_dependency(%q<rspec>, ["~> 2.5.0"])
      s.add_development_dependency(%q<bundler>, ["~> 1.0.0"])
      s.add_development_dependency(%q<jeweler>, ["~> 1.5.2"])
      s.add_development_dependency(%q<rcov>, [">= 0"])
      s.add_development_dependency(%q<rspec>, ["> 1.2.3"])
    else
      s.add_dependency(%q<rspec>, ["~> 2.5.0"])
      s.add_dependency(%q<bundler>, ["~> 1.0.0"])
      s.add_dependency(%q<jeweler>, ["~> 1.5.2"])
      s.add_dependency(%q<rcov>, [">= 0"])
      s.add_dependency(%q<rspec>, ["> 1.2.3"])
    end
  else
    s.add_dependency(%q<rspec>, ["~> 2.5.0"])
    s.add_dependency(%q<bundler>, ["~> 1.0.0"])
    s.add_dependency(%q<jeweler>, ["~> 1.5.2"])
    s.add_dependency(%q<rcov>, [">= 0"])
    s.add_dependency(%q<rspec>, ["> 1.2.3"])
  end
end

